### ISSUE TITLE
Only corrupted files with 0 bytes

### ISSUE THREAD

**Issue by ishiharas** [UnicodingUnicorn/mangadex-downloader#1]
Hello,
Today I tried to use your tool on my MacBook, running on macOS Catalina 10.15.4
I installed the GO binaries freshly, running the following version:
`go version go1.14.6 darwin/amd64` 

Afterwards I initialized the process with the following command:
`./mangadex-downloader -u https://mangadex.org/title/3996/akatsuki-no-yona -r 43-60`

This resulted in folders with correct chapter names, but only corrupted files.

<img width="533" alt="image" src="https://user-images.githubusercontent.com/43359029/89962395-da811180-dc44-11ea-81d9-203ba1aa84b3.png">

It would be great, if you could look into this. Cheers!

**Comment by UnicodingUnicorn** [comment]
Hello, thanks for bringing this to my attention and sorry for taking so long to reply! It turns out that somewhere along the way sometime ago mangadex decided to add a trailing slash in the URL provided for the S3 host in its API, which mucked everything up here since I just used string concatenation to construct the retrieval URL.

In any case, it should be fixed now.
